###
GET http://localhost:9001/api/pruebas HTTP/1.1

###
GET http://localhost:9001/api/pruebas/prod_id HTTP/1.1

###
POST http://localhost:9001/api/pruebas HTTP/1.1
Content-Type: application/json

{

    "producto":"prod 4",
    "PCompra":4,
    "PVenta":4,
    "unidades":4
}

###
DELETE http://localhost:9001/api/pruebas/prod_id/3 HTTP/1.1

###
PUT http://localhost:9001/api/pruebas/prod_id/3 HTTP/1.1
Content-Type: application/json

{
    "producto":"prueba producto 3 editado",
    "PCompra":3,
    "PVenta":3,
    "unidades":3
}